using CSV, DataFrames

#Function to calculate the energy production under a cost of 35$/MWh.
function RLCOEX(reg)
S=CSV.read("$(reg)_VRE.csv",DataFrame);
S1=Matrix(S);
SS=findfirst(x -> x<=35, S1[:,1])
if SS == nothing
SSS=0
else
SS=findfirst(x -> x>=35, S1[:,1])
SSS=S1[:,3][SS]
end
return SSS
end

Energyproduction=[RLCOEX("Afghanistan")
RLCOEX("Albania")
RLCOEX("Algeria")
RLCOEX("Angola")
RLCOEX("Argentina")
RLCOEX("Armenia")
RLCOEX("Australia")
RLCOEX("Austria")
RLCOEX("Azerbaijan")
RLCOEX("Bangladesh")
RLCOEX("Belarus")
RLCOEX("Belgium")
RLCOEX("Belize")
RLCOEX("Benin")
RLCOEX("Bhutan")
RLCOEX("Bolivia")
RLCOEX("Bosnia and Herzegovina")
RLCOEX("Botswana")
RLCOEX("Brazil")
RLCOEX("Brunei")
RLCOEX("Bulgaria")
RLCOEX("Burkina Faso")
RLCOEX("Burundi")
RLCOEX("Cambodia")
RLCOEX("Cameroon")
RLCOEX("Canada")
RLCOEX("Central African Republic")
RLCOEX("Chad")
RLCOEX("Chile")
RLCOEX("China")
RLCOEX("Colombia")
RLCOEX("Costa Rica")
RLCOEX("Côte d'Ivoire")
RLCOEX("Croatia")
RLCOEX("Cuba")
RLCOEX("Cyprus")
RLCOEX("Czech Republic")
RLCOEX("Democratic Republic of the Congo")
RLCOEX("Denmark")
RLCOEX("Djibouti")
RLCOEX("Dominican Republic")
RLCOEX("Ecuador")
RLCOEX("Egypt")
RLCOEX("El Salvador")
RLCOEX("Equatorial Guinea")
RLCOEX("Eritrea")
RLCOEX("Estonia")
RLCOEX("Ethiopia")
RLCOEX("Finland")
RLCOEX("France")
RLCOEX("French Guiana")
RLCOEX("Gabon")
RLCOEX("Gambia")
RLCOEX("Georgia")
RLCOEX("Germany")
RLCOEX("Ghana")
RLCOEX("Greece")
RLCOEX("Guatemala")
RLCOEX("Guinea")
RLCOEX("Guinea-Bissau")
RLCOEX("Guyana")
RLCOEX("Haiti")
RLCOEX("Honduras")
RLCOEX("Hungary")
RLCOEX("Iceland")
RLCOEX("India")
RLCOEX("Indonesia")
RLCOEX("Iran")
RLCOEX("Iraq")
RLCOEX("Ireland")
RLCOEX("Israel")
RLCOEX("Italy")
RLCOEX("Jamaica")
RLCOEX("Japan")
RLCOEX("Jordan")
RLCOEX("Kazakhstan")
RLCOEX("Kenya")
RLCOEX("Kosovo")
RLCOEX("Kuwait")
RLCOEX("Kyrgyzstan")
RLCOEX("Laos")
RLCOEX("Latvia")
RLCOEX("Lebanon")
RLCOEX("Lesotho")
RLCOEX("Liberia")
RLCOEX("Libya")
RLCOEX("Lithuania")
RLCOEX("Luxembourg")
RLCOEX("Macedonia")
RLCOEX("Madagascar")
RLCOEX("Malawi")
RLCOEX("Malaysia")
RLCOEX("Mali")
RLCOEX("Mauritania")
RLCOEX("Mexico")
RLCOEX("Moldova")
RLCOEX("Mongolia")
RLCOEX("Montenegro")
RLCOEX("Morocco")
RLCOEX("Mozambique")
RLCOEX("Myanmar")
RLCOEX("Namibia")
RLCOEX("Nepal")
RLCOEX("Netherlands")
RLCOEX("New Zealand")
RLCOEX("Nicaragua")
RLCOEX("Niger")
RLCOEX("Nigeria")
RLCOEX("North Korea")
RLCOEX("Norway")
RLCOEX("Oman")
RLCOEX("Pakistan")
RLCOEX("Palestina")
RLCOEX("Panama")
RLCOEX("Papua New Guinea")
RLCOEX("Paraguay")
RLCOEX("Peru")
RLCOEX("Philippines")
RLCOEX("Poland")
RLCOEX("Portugal")
RLCOEX("Puerto Rico")
RLCOEX("Qatar")
RLCOEX("Republic of Congo")
RLCOEX("Romania")
RLCOEX("Russia")
RLCOEX("Rwanda")
RLCOEX("Saudi Arabia")
RLCOEX("Senegal")
RLCOEX("Serbia")
RLCOEX("Sierra Leone")
RLCOEX("Slovakia")
RLCOEX("Slovenia")
RLCOEX("Somalia")
RLCOEX("South Africa")
RLCOEX("South Korea")
RLCOEX("South Sudan")
RLCOEX("Spain")
RLCOEX("Sri Lanka")
RLCOEX("Sudan")
RLCOEX("Suriname")
RLCOEX("Swaziland")
RLCOEX("Sweden")
RLCOEX("Switzerland")
RLCOEX("Syria")
RLCOEX("Taiwan")
RLCOEX("Tajikistan")
RLCOEX("Tanzania")
RLCOEX("Thailand")
RLCOEX("Timor-Leste")
RLCOEX("Togo")
RLCOEX("Trinidad and Tobago")
RLCOEX("Tunisia")
RLCOEX("Turkey")
RLCOEX("Turkmenistan")
RLCOEX("Uganda")
RLCOEX("Ukraine")
RLCOEX("United Kingdom")
RLCOEX("United States")
RLCOEX("Uruguay")
RLCOEX("Uzbekistan")
RLCOEX("Venezuela")
RLCOEX("Vietnam")
RLCOEX("Western Sahara")
RLCOEX("Yemen")
RLCOEX("Zambia")
RLCOEX("Zimbabwe")
RLCOEX("Australiaa")
RLCOEX("Australiab")
RLCOEX("Australiac")
RLCOEX("Australiad")
RLCOEX("Australiae")
RLCOEX("Brazila")
RLCOEX("Brazilb")
RLCOEX("Brazilc")
RLCOEX("Brazild")
RLCOEX("Brazile")
RLCOEX("Brazilf")
RLCOEX("Canadaa")
RLCOEX("Canadab")
RLCOEX("Canadac")
RLCOEX("Canadad")
RLCOEX("Canadae")
RLCOEX("Canadaf")
RLCOEX("Chinaa")
RLCOEX("Chinab")
RLCOEX("Chinac")
RLCOEX("Chinad")
RLCOEX("Chinae")
RLCOEX("Chinaf")
RLCOEX("Indiaa")
RLCOEX("Indiab")
RLCOEX("Indiac")
RLCOEX("Indiad")
RLCOEX("Indiae")
RLCOEX("Indiaf")
RLCOEX("Indonesiaa")
RLCOEX("Indonesiab")
RLCOEX("Indonesiac")
RLCOEX("Indonesiad")
RLCOEX("Indonesiae")
RLCOEX("Irana")
RLCOEX("Iranb")
RLCOEX("Iranc")
RLCOEX("Irand")
RLCOEX("Kazakhstana")
RLCOEX("Kazakhstanb")
RLCOEX("Kazakhstanc")
RLCOEX("Kazakhstand")
RLCOEX("Mexicoa")
RLCOEX("Mexicob")
RLCOEX("Mexicoc")
RLCOEX("Mexicod")
RLCOEX("Mexicoe")
RLCOEX("Pakistana")
RLCOEX("Pakistanb")
RLCOEX("Pakistanc")
RLCOEX("Pakistand")
RLCOEX("Russiaa")
RLCOEX("Russiab")
RLCOEX("Russiac")
RLCOEX("Russiad")
RLCOEX("Russiae")
RLCOEX("Russiaf")
RLCOEX("Russiag")
RLCOEX("Russiah")
RLCOEX("Saudi Arabiaa")
RLCOEX("Saudi Arabiab")
RLCOEX("Saudi Arabiac")
RLCOEX("Saudi Arabiad")
RLCOEX("United Statesa")
RLCOEX("United Statesb")
RLCOEX("United Statesc")
RLCOEX("United Statesd")
RLCOEX("United Statese")
RLCOEX("United Statesf")
RLCOEX("United Statesg")
RLCOEX("United Statesh")
RLCOEX("United Statesi")
RLCOEX("United Statesj")]'
Energy_production = DataFrame(Energyproduction,:auto)
CSV.write("Energy_production_below35.csv",Energy_production)

#The potential energy export volume is calculated by subtracting the domestic energy demand from the energy production calculated above.
