using CSV, DataFrames
function CSVOUT(reg)
S=CSV.read("$(reg)_VRE.csv",DataFrame);
SS=Matrix(S);
return SS
end
#Merge the renewable generation data for the entire world
csvout=[CSVOUT("Afghanistan")[:,1:3]
CSVOUT("Albania")[:,1:3]
CSVOUT("Algeria")[:,1:3]
CSVOUT("Angola")[:,1:3]
CSVOUT("Argentina")[:,1:3]
CSVOUT("Armenia")[:,1:3]
CSVOUT("Austria")[:,1:3]
CSVOUT("Azerbaijan")[:,1:3]
CSVOUT("Bangladesh")[:,1:3]
CSVOUT("Belarus")[:,1:3]
CSVOUT("Belgium")[:,1:3]
CSVOUT("Belize")[:,1:3]
CSVOUT("Benin")[:,1:3]
CSVOUT("Bhutan")[:,1:3]
CSVOUT("Bolivia")[:,1:3]
CSVOUT("Bosnia and Herzegovina")[:,1:3]
CSVOUT("Botswana")[:,1:3]
CSVOUT("Brunei")[:,1:3]
CSVOUT("Bulgaria")[:,1:3]
CSVOUT("Burkina Faso")[:,1:3]
CSVOUT("Burundi")[:,1:3]
CSVOUT("Cambodia")[:,1:3]
CSVOUT("Cameroon")[:,1:3]
CSVOUT("Central African Republic")[:,1:3]
CSVOUT("Chad")[:,1:3]
CSVOUT("Chile")[:,1:3]
CSVOUT("Colombia")[:,1:3]
CSVOUT("Costa Rica")[:,1:3]
CSVOUT("Côte d'Ivoire")[:,1:3]
CSVOUT("Croatia")[:,1:3]
CSVOUT("Cuba")[:,1:3]
CSVOUT("Cyprus")[:,1:3]
CSVOUT("Czech Republic")[:,1:3]
CSVOUT("Democratic Republic of the Congo")[:,1:3]
CSVOUT("Denmark")[:,1:3]
CSVOUT("Djibouti")[:,1:3]
CSVOUT("Dominican Republic")[:,1:3]
CSVOUT("Ecuador")[:,1:3]
CSVOUT("Egypt")[:,1:3]
CSVOUT("El Salvador")[:,1:3]
CSVOUT("Equatorial Guinea")[:,1:3]
CSVOUT("Eritrea")[:,1:3]
CSVOUT("Estonia")[:,1:3]
CSVOUT("Ethiopia")[:,1:3]
CSVOUT("Finland")[:,1:3]
CSVOUT("France")[:,1:3]
CSVOUT("French Guiana")[:,1:3]
CSVOUT("Gabon")[:,1:3]
CSVOUT("Gambia")[:,1:3]
CSVOUT("Georgia")[:,1:3]
CSVOUT("Germany")[:,1:3]
CSVOUT("Ghana")[:,1:3]
CSVOUT("Greece")[:,1:3]
CSVOUT("Guatemala")[:,1:3]
CSVOUT("Guinea")[:,1:3]
CSVOUT("Guinea-Bissau")[:,1:3]
CSVOUT("Guyana")[:,1:3]
CSVOUT("Haiti")[:,1:3]
CSVOUT("Honduras")[:,1:3]
CSVOUT("Hungary")[:,1:3]
CSVOUT("Iceland")[:,1:3]
CSVOUT("Iraq")[:,1:3]
CSVOUT("Ireland")[:,1:3]
CSVOUT("Israel")[:,1:3]
CSVOUT("Italy")[:,1:3]
CSVOUT("Jamaica")[:,1:3]
CSVOUT("Japan")[:,1:3]
CSVOUT("Jordan")[:,1:3]
CSVOUT("Kenya")[:,1:3]
CSVOUT("Kosovo")[:,1:3]
CSVOUT("Kuwait")[:,1:3]
CSVOUT("Kyrgyzstan")[:,1:3]
CSVOUT("Laos")[:,1:3]
CSVOUT("Latvia")[:,1:3]
CSVOUT("Lebanon")[:,1:3]
CSVOUT("Lesotho")[:,1:3]
CSVOUT("Liberia")[:,1:3]
CSVOUT("Libya")[:,1:3]
CSVOUT("Lithuania")[:,1:3]
CSVOUT("Luxembourg")[:,1:3]
CSVOUT("Macedonia")[:,1:3]
CSVOUT("Madagascar")[:,1:3]
CSVOUT("Malawi")[:,1:3]
CSVOUT("Malaysia")[:,1:3]
CSVOUT("Mali")[:,1:3]
CSVOUT("Mauritania")[:,1:3]
CSVOUT("Moldova")[:,1:3]
CSVOUT("Mongolia")[:,1:3]
CSVOUT("Montenegro")[:,1:3]
CSVOUT("Morocco")[:,1:3]
CSVOUT("Mozambique")[:,1:3]
CSVOUT("Myanmar")[:,1:3]
CSVOUT("Namibia")[:,1:3]
CSVOUT("Nepal")[:,1:3]
CSVOUT("Netherlands")[:,1:3]
CSVOUT("New Zealand")[:,1:3]
CSVOUT("Nicaragua")[:,1:3]
CSVOUT("Niger")[:,1:3]
CSVOUT("Nigeria")[:,1:3]
CSVOUT("North Korea")[:,1:3]
CSVOUT("Norway")[:,1:3]
CSVOUT("Oman")[:,1:3]
CSVOUT("Palestina")[:,1:3]
CSVOUT("Panama")[:,1:3]
CSVOUT("Papua New Guinea")[:,1:3]
CSVOUT("Paraguay")[:,1:3]
CSVOUT("Peru")[:,1:3]
CSVOUT("Philippines")[:,1:3]
CSVOUT("Poland")[:,1:3]
CSVOUT("Portugal")[:,1:3]
CSVOUT("Puerto Rico")[:,1:3]
CSVOUT("Qatar")[:,1:3]
CSVOUT("Republic of Congo")[:,1:3]
CSVOUT("Romania")[:,1:3]
CSVOUT("Rwanda")[:,1:3]
CSVOUT("Senegal")[:,1:3]
CSVOUT("Serbia")[:,1:3]
CSVOUT("Sierra Leone")[:,1:3]
CSVOUT("Slovakia")[:,1:3]
CSVOUT("Slovenia")[:,1:3]
CSVOUT("Somalia")[:,1:3]
CSVOUT("South Africa")[:,1:3]
CSVOUT("South Korea")[:,1:3]
CSVOUT("South Sudan")[:,1:3]
CSVOUT("Spain")[:,1:3]
CSVOUT("Sri Lanka")[:,1:3]
CSVOUT("Sudan")[:,1:3]
CSVOUT("Suriname")[:,1:3]
CSVOUT("Swaziland")[:,1:3]
CSVOUT("Sweden")[:,1:3]
CSVOUT("Switzerland")[:,1:3]
CSVOUT("Syria")[:,1:3]
CSVOUT("Taiwan")[:,1:3]
CSVOUT("Tajikistan")[:,1:3]
CSVOUT("Tanzania")[:,1:3]
CSVOUT("Thailand")[:,1:3]
CSVOUT("Timor-Leste")[:,1:3]
CSVOUT("Togo")[:,1:3]
CSVOUT("Trinidad and Tobago")[:,1:3]
CSVOUT("Tunisia")[:,1:3]
CSVOUT("Turkey")[:,1:3]
CSVOUT("Turkmenistan")[:,1:3]
CSVOUT("Uganda")[:,1:3]
CSVOUT("Ukraine")[:,1:3]
CSVOUT("United Kingdom")[:,1:3]
CSVOUT("Uruguay")[:,1:3]
CSVOUT("Uzbekistan")[:,1:3]
CSVOUT("Venezuela")[:,1:3]
CSVOUT("Vietnam")[:,1:3]
CSVOUT("Western Sahara")[:,1:3]
CSVOUT("Yemen")[:,1:3]
CSVOUT("Zambia")[:,1:3]
CSVOUT("Zimbabwe")[:,1:3]
CSVOUT("Australiaa")[:,1:3]
CSVOUT("Australiab")[:,1:3]
CSVOUT("Australiac")[:,1:3]
CSVOUT("Australiad")[:,1:3]
CSVOUT("Australiae")[:,1:3]
CSVOUT("Brazila")[:,1:3]
CSVOUT("Brazilb")[:,1:3]
CSVOUT("Brazilc")[:,1:3]
CSVOUT("Brazild")[:,1:3]
CSVOUT("Brazile")[:,1:3]
CSVOUT("Brazilf")[:,1:3]
CSVOUT("Canadaa")[:,1:3]
CSVOUT("Canadab")[:,1:3]
CSVOUT("Canadac")[:,1:3]
CSVOUT("Canadad")[:,1:3]
CSVOUT("Canadae")[:,1:3]
CSVOUT("Canadaf")[:,1:3]
CSVOUT("Chinaa")[:,1:3]
CSVOUT("Chinab")[:,1:3]
CSVOUT("Chinac")[:,1:3]
CSVOUT("Chinad")[:,1:3]
CSVOUT("Chinae")[:,1:3]
CSVOUT("Chinaf")[:,1:3]
CSVOUT("Indiaa")[:,1:3]
CSVOUT("Indiab")[:,1:3]
CSVOUT("Indiac")[:,1:3]
CSVOUT("Indiad")[:,1:3]
CSVOUT("Indiae")[:,1:3]
CSVOUT("Indiaf")[:,1:3]
CSVOUT("Indonesiaa")[:,1:3]
CSVOUT("Indonesiab")[:,1:3]
CSVOUT("Indonesiac")[:,1:3]
CSVOUT("Indonesiad")[:,1:3]
CSVOUT("Indonesiae")[:,1:3]
CSVOUT("Irana")[:,1:3]
CSVOUT("Iranb")[:,1:3]
CSVOUT("Iranc")[:,1:3]
CSVOUT("Irand")[:,1:3]
CSVOUT("Kazakhstana")[:,1:3]
CSVOUT("Kazakhstanb")[:,1:3]
CSVOUT("Kazakhstanc")[:,1:3]
CSVOUT("Kazakhstand")[:,1:3]
CSVOUT("Mexicoa")[:,1:3]
CSVOUT("Mexicob")[:,1:3]
CSVOUT("Mexicoc")[:,1:3]
CSVOUT("Mexicod")[:,1:3]
CSVOUT("Mexicoe")[:,1:3]
CSVOUT("Pakistana")[:,1:3]
CSVOUT("Pakistanb")[:,1:3]
CSVOUT("Pakistanc")[:,1:3]
CSVOUT("Pakistand")[:,1:3]
CSVOUT("Russiaa")[:,1:3]
CSVOUT("Russiab")[:,1:3]
CSVOUT("Russiac")[:,1:3]
CSVOUT("Russiad")[:,1:3]
CSVOUT("Russiae")[:,1:3]
CSVOUT("Russiaf")[:,1:3]
CSVOUT("Russiag")[:,1:3]
CSVOUT("Russiah")[:,1:3]
CSVOUT("Saudi Arabiaa")[:,1:3]
CSVOUT("Saudi Arabiab")[:,1:3]
CSVOUT("Saudi Arabiac")[:,1:3]
CSVOUT("Saudi Arabiad")[:,1:3]
CSVOUT("United Statesa")[:,1:3]
CSVOUT("United Statesb")[:,1:3]
CSVOUT("United Statesc")[:,1:3]
CSVOUT("United Statesd")[:,1:3]
CSVOUT("United Statese")[:,1:3]
CSVOUT("United Statesf")[:,1:3]
CSVOUT("United Statesg")[:,1:3]
CSVOUT("United Statesh")[:,1:3]
CSVOUT("United Statesi")[:,1:3]
CSVOUT("United Statesj")[:,1:3]
]

energy=csvout[:,3]
share=csvout[:,2]
lcoe=csvout[:,1]

x = sortperm(lcoe)
y = cumsum(energy[x])
supply = DataFrame()
supply.A = y
supply.B = sort(lcoe)
supply
#Save renewable supply data with country-specific discount rate
CSV.write("supplyworld country-specific discount rate.csv",supply)
